version: '3.3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  charmingEpg:
    build: .
    ports:
      - "30008:80"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: postgres:5432
    depends_on:
      - postgres